---
- hosts: all
  become: yes
  tasks:
    - name: Remove Old hosts file entry
      vars:
        - names: "{% for host in groups['kubecluster'] %} {{ hostvars[host]['ansible_hostname']}} {% endfor %} "
      lineinfile:
        dest: /tmp/hosts
        regexp: "{{ item }}"
        state: absent
        backup: yes
        unsafe_writes: yes
      with_items: "{{ names.split( ) }}"
    - name: Hosts populate inventory into hosts file
      lineinfile:
        path: /tmp/hosts
        line: |-
                {% for host in groups['kubecluster'] %}
                {{ hostvars[host]['ansible_default_ipv4']['address'] }} {{ hostvars[host]['ansible_hostname'] }}
                {% endfor %}
        state: present
        create: yes
        backup: yes
        unsafe_writes: yes
