- name: Check if kubeadmin initiated
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeconfig
  when: "'kubemaster' in group_names"
  tags:
    - configurekubectl
- name: Setup Kubectl
  vars:
    homedir: "/home/{{ kubeuser }}"
    kubeconfpath: "{{ homedir }}/.kube"
    kubeconffile: "{{ kubeconfpath }}/config"
  block:
    - name: Check if kube config directory exists
      file:
        path: "{{ kubeconfpath }}"
        state: directory
      become_user: "{{ kubeuser }}"
      become: true
    - name: Copy Kubeadmin conf to "{{ kubeconffile }}"
      shell: 'cp /etc/kubernetes/admin.conf {{ kubeconffile }}'
    - name: Set permission on Kube config
      file:
        path: "{{ kubeconffile }}"
        owner: "{{ kubeuser }}"
        group: "{{ kubeuser }}"
  when:
    - kubeconfig.stat.exists == true
    - "'kubemaster' in group_names"
  ignore_errors: yes
  tags:
    - configurekubectl
