- name: Reset Kubernetes Cluster if present
  shell: "kubeadm reset --force"
  register: kubereset
  when: "'kubemaster' in group_names"
- name: Setup Kuberntes Cluster
  shell: |
    kubeadm init \
    --pod-network-cidr {{ pod_network_cidr }} \
    --token {{ kube_token }}
  register: output_kubeadm
  when: 
    - kubereset is succeeded
    - "'kubemaster' in group_names"
  tags:
    - setupmaster
- debug: msg="{{ output_kubeadm | to_nice_json }}"
