- name: Remove kubenode from cluster if already joined
  shell: "kubeadm reset --force"
  register: reset_cluster
  ignore_errors: yes
  failed_when: "'remove them manually' not in reset_cluster.stdout"
  tags:
    - kubejoin
  when: "'kubenodes' in group_names"
- name: Join Kube Cluster
  vars:
    - kubenodeslist: "{% for hostmember in groups['kubenodes'] %} {{ hostvars[hostmember]['ansible_hostname']}} {% endfor %} "
  shell: |
      kubeadm join --token {{ kube_token }} \
      --discovery-token-unsafe-skip-ca-verification \
      "{{ hostvars['kubemaster']['ansible_default_ipv4']['address'] }}":"{{ kube_api_secure_port }}" || \
      echo "{{ item }}" > /tmp/name
  when:
    - reset_cluster is succeeded
    - "'kubenodes' in group_names"
  with_items: "{{ kubenodeslist.split( ) }}"
  tags:
    - kubejoin
