- name: Configure Kubernetes Yum Repository
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo
  when: "'kubecluster' in group_names"
- name: Install Kubernetes packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - "{{ kubernetes_packages }}"
  when: "'kubecluster' in group_names"
- name: Configure sysctl for kubernetes\
  sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
  when: "'kubecluster' in group_names"
- name: Load br netfilter
  modprobe:
    name: br_netfilter
    state: present
  when: "'kubecluster' in group_names"
- name: Configure cgroups for Kubernetes
  block:
    - lineinfile:
        path: /etc/default/kubelet
        line: "KUBELET_EXTRA_ARGS=--cgroup-driver=systemd"
        create: yes
    - systemd:
        daemon_reload: yes
        name: kubelet
        state: restarted
        enabled: yes
  when: "'kubecluster' in group_names"
