- name: Install required dependent packages for Docker
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - "{{ docker_dependent_packages }}"
  when: "'kubecluster' in group_names"
- name: Configure Docker yum repository
  template:
    src: docker-ce.repo.j2
    dest: /etc/yum.repos.d/docker-ce.repo
  when: "'kubecluster' in group_names"
- name: Update existing packages
  yum:
    name: "*"
    state: latest
    update_cache: yes
    disablerepo: docker-ce-stable
  when: "'kubecluster' in group_names"
- name: Installing Docker Packages
  yum:
    name: docker-ce-18.06.2.ce
    state: installed
  when: "'kubecluster' in group_names"
- name: Configure Docker
  block:
    - file:
        state: directory
        path: /etc/docker
    - template:
        src: docker-daemon.json.j2
        dest: /etc/docker/daemon.json
    - file:
        state: directory
        path: /etc/systemd/system/docker.service.d
    - systemd:
        daemon_reload: yes
        name: docker
        state: restarted
        enabled: yes
  when: "'kubecluster' in group_names"
