- name: Remove Old hosts file entry
  vars:
    - names: "{% for host in groups['kubecluster'] %} {{ hostvars[host]['ansible_hostname']}} {% endfor %} "
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ item }}"
    state: absent
    backup: yes
    unsafe_writes: yes
  with_items: "{{ names.split( ) }}"
  # when: "'kubecluster' in group_names"
  tags:
    - removehostname
    - sethosts
- name: Hosts populate inventory into hosts file
  lineinfile:
    path: /etc/hosts
    line: |-
             {% for host in groups['kubecluster'] %}
             {{ hostvars[host]['ansible_default_ipv4']['address'] }} {{ hostvars[host]['inventory_hostname'] }}
             {% endfor %}
    state: present
    create: yes
    backup: yes
    unsafe_writes: yes
  ignore_errors: yes
  when: "'kubecluster' in group_names"
  tags:
    - sethostsfile
    - sethosts
- name: Update Hostname
  hostname:
    name: "{{ inventory_hostname }}"
  when: "'kubecluster' in group_names"
  tags:
    - sethostname
    - sethosts
