- name: Turn off swap space
  block:
    - name: Turn off Swap partitions
      command: swapoff -a
    - name: Remove SWAP entry from fstab
      lineinfile:
        path: /etc/fstab
        regexp: "swap"
        state: absent
  when: "'kubecluster' in group_names"
